# Generated by Django 5.1 on 2024-08-22 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 8, 22, 6, 34, 38, 963796, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
