# Generated by Django 5.1 on 2024-08-23 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 8, 23, 12, 12, 31, 28867, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
