# Generated by Django 5.1 on 2024-08-23 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 8, 23, 13, 8, 5, 312993, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
